# Q-1: Create a random 3x4 matrix with value between 0-100. And perform below tasks

In [6]:
arr=np.random.randint(0,100,(4,3))
print(arr)
print(np.sort(arr))
print(arr[arr[:,1].argsort()])
print(np.array(sorted(arr, key = lambda x: max(x))))
#4
print(np.sort(arr, axis = None).reshape(4,3))


[[ 5 94 11]
 [10 43 33]
 [72 48 16]
 [50 44 85]]
[[ 5 11 94]
 [10 33 43]
 [16 48 72]
 [44 50 85]]
[[10 43 33]
 [50 44 85]
 [72 48 16]
 [ 5 94 11]]
[[10 43 33]
 [72 48 16]
 [50 44 85]
 [ 5 94 11]]
[[ 5 10 11]
 [16 33 43]
 [44 48 50]
 [72 85 94]]


In [2]:
import numpy as np

# Q-2: There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.

In [7]:
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])

In [8]:
np.unique(arr,axis=0)

array([[0, 9, 1, 2, 8, 8],
       [1, 2, 3, 3, 1, 1],
       [1, 2, 3, 8, 8, 8]])

In [9]:
np.unique(arr,axis=1)

array([[1, 1, 2, 3, 3],
       [0, 8, 9, 1, 2],
       [1, 8, 2, 3, 8],
       [1, 1, 2, 3, 3]])

In [10]:
arr = np.array([[1,2,3,3,1,1],
               [0,9,1,2,8,8],
               [1,2,3,8,8,8],
               [1,2,3,3,1,1],
               [0,6,1,2,11,7],
               [10,19,14,-2,8,-1]])

In [11]:
np.flip(arr,axis=[0,1])

array([[-1,  8, -2, 14, 19, 10],
       [ 7, 11,  2,  1,  6,  0],
       [ 1,  1,  3,  3,  2,  1],
       [ 8,  8,  8,  3,  2,  1],
       [ 8,  8,  2,  1,  9,  0],
       [ 1,  1,  3,  3,  2,  1]])

# Get row numbers of NumPy array having element larger than X.

In [14]:
arr = [[1,2,3,4,5], 
      [10,-3,30,4,5], 
      [3,2,5,-4,5], 
      [9,7,3,6,5]] 

X = 6

np.any(np.any(arr >X, axis = 1))

TypeError: '>' not supported between instances of 'list' and 'int'

In [16]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

np.concatenate([arr1, arr2, arr3])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])