In [1]:
import numpy as np

In [5]:
# Create a null vector of size 10 but the fifth value which is 1
a=np.zeros(10)
a[4]=1
print(a)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [2]:
# # Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b)
# and print the array and avg of the array.
a=int(input('enter the number'))
b=int(input('enter the number'))
d=np.array([a,b])
print(d)
c=np.random.random(d)
print(np.mean(c))


enter the number5
enter the number8
[5 8]
0.5285409489587792


In [12]:
# Write a function to create a 2d array with 1 on the border and 0 inside.
# Take 2-D array shape as (a,b) as parameter to function.
def create_border_array(a, b):
    # Initialize the array with zeros
    array = np.zeros((a, b), dtype=int)
    
    # Set the borders to 1 using slicing
    array[0, :] = 1
    array[-1, :] = 1
    array[:, 0] = 1
    array[:, -1] = 1
    
    return array

# Example usage
a = 5
b = 7
border_array = create_border_array(a, b)
print(border_array)

[[1 1 1 1 1 1 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 1 1 1 1 1 1]]


In [4]:
# Create a vector of size 10 with values ranging from 0 to 1, both excluded
import numpy as np

# Create a vector of size 10 with values ranging from 0 to 1, both excluded
vector = np.linspace(0, 1, 12)[1:3]

print(vector)

[0.09090909 0.18181818]


In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
# create a 5x5 matrix with row values ranging from 0 to 4.
z=np.zeros((5,5))
z+=np.arange(5)
z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [33]:
# : Consider a random integer (in range 1 to 100) vector with shape (10,2) representing coordinates, and 
#     coordinates of a point as array is given. 
#     Create an array of distance of each point in the random vectros from the given point.
#     Distance array should be interger type
a=np.random.randint(1,101,(10,2))
p=np.array([2,3])
np.sqrt(np.sum((a-p)**2,axis=1)).astype(int)

array([ 18,  94,  95, 107,  79,  53,  88, 107,  69,  31])

In [34]:
# Consider a (6,7,8) shape array, 
# what is the index (x,y,z) of the 100th element?
np.unravel_index(100,(6,7,8))

(1, 5, 4)

In [5]:
#  Elements count
# Count the number of elements of a numpy array.
a=np.array([1,2])
a.size

2

In [6]:
#Code here
def softmax(arr):
    if type(arr) != np.ndarray:
        raise TypeError("Requires Numpy Array")
    elif arr.ndim > 1:
        raise TypeError("Requires 1D Array")
    s = np.sum(np.exp(arr))
    return np.exp(arr)/s
softmax(np.array([86.03331084, 37.7285648,  48.64908087, 87.16563062, 38.40852563, 37.20006318]))

array([2.43733248e-01, 2.56112114e-22, 1.41628283e-17, 7.56266752e-01,
       5.05514197e-22, 1.50974911e-22])

In [7]:
import numpy as np

def vertical_stack(*arrays):
    if not all(isinstance(arr, np.ndarray) for arr in arrays):
        raise ValueError("All inputs must be numpy arrays")
    
    return np.vstack(arrays)

# Example usage
try:
    array1 = np.array([[1, 2], [3, 4]])
    array2 = np.array([[5, 6], [7, 8]])
    array3 = np.array([[9, 10]])

    result = vertical_stack(array1, array2, array3)
    print(result)
except ValueError as e:
    print(e)


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [12]:
# Subtract the mean of each row from a matrix.
a=np.random.random((5,4))
print(a)
v=a-a.mean(axis=1,keepdims= True)
print(v)

[[0.46834981 0.70067465 0.34438319 0.81405022]
 [0.12354288 0.72113703 0.75457052 0.14391747]
 [0.49734936 0.11791606 0.26209238 0.6670842 ]
 [0.99818411 0.71546311 0.75804845 0.22300166]
 [0.32565699 0.09700516 0.49237065 0.09722915]]
[[-0.11351465  0.11881018 -0.23748128  0.23218575]
 [-0.31224909  0.28534505  0.31877855 -0.2918745 ]
 [ 0.11123886 -0.26819444 -0.12401812  0.2809737 ]
 [ 0.32450978  0.04178878  0.08437411 -0.45067267]
 [ 0.0725915  -0.15606033  0.23930517 -0.15583634]]


In [15]:
a=np.arange(9).reshape((3,3))
print(a)
a[:,[0,2,1]]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])